
# services:
#   db:
#     container_name: postgres-local
#     image: postgres:latest
#     environment:
#       POSTGRES_PASSWORD: local
#     ports:
#       - '5432:5432'

services:
  pg:
    container_name: postgres-local
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: nestjs
      POSTGRES_DB: zeroone
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
